### PR TITLE
Better handle errors from the client and detect multiple operations

### LINKED ISSUE #431: `generate-persisted-query-manifest` : Hard to debug violations; Can docs with multiple root-level mutations be allowed?
Recently while generating a persisted query manifest for a project with 400+ files to scan for operations, I got the following error: 
```
Invariant Violation: An error occurred! For more details, see the full error text at https://go.apollo.dev/c/err#%7B%22version%22%3A%223.9.11%22%2C%22message%22%3A76%2C%22args%22%3A%5B%222%22%5D%7D
    at new InvariantError (/my-app/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.cjs:16:28)
    at Object.invariant (/my-app/node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.cjs:28:15)
    at Object.invariant (/my-app/node_modules/@apollo/client/utilities/globals/globals.cjs:64:21)
    at checkDocument (/my-app/node_modules/@apollo/client/utilities/utilities.cjs:461:13)
    at DocumentTransform.performWork (/my-app/node_modules/@apollo/client/utilities/utilities.cjs:575:9)
    at DocumentTransform.transformDocument (/my-app/node_modules/@apollo/client/utilities/utilities.cjs:582:40)
    at QueryManager.transform (/my-app/node_modules/@apollo/client/core/core.cjs:1681:39)
    at QueryManager.query (/my-app/node_modules/@apollo/client/core/core.cjs:1740:99)
    at ApolloClient.query (/my-app/node_modules/@apollo/client/core/core.cjs:2477:34)
    at generatePersistedQueryManifest (/my-app/node_modules/@apollo/generate-persisted-query-manifest/dist/index.js:332:30) {
  framesToPop: 1
}
```

It was confusing that I was receiving an Apollo Client error.  I followed the link to the error page and found this: 
image

With over 400 files with potential operations to choose from, this provided no insight into where the problem was.  

I was able to find the culprit by following the strace to [here](https://github.com/apollographql/apollo-client/blob/main/src/utilities/graphql/getFromAST.ts#L38).

By adding a conditional breakpoint on a this line (`operations.length > 1`) I was able to get the operation document, which I then used to search my project and find the culprit, which ended up being two mutations side by side that looked similar to this: 
```
graphqlOperations.mutations = gql`
  mutation RegisterItem(
    $input: RegisterItemInput
  ) {
    registerItem(input: $input) {
      status
      message
    }
  }
  mutation SyncItem(
    $input: SyncItemInput
  ) {
    syncItem(input: $input) {
      isSuccess
      message
    }
  }
`;
```

The above method of debugging "invariant violations" is not ergonomic for users.  It would be great if the operation name and the filename/location were surfaced here.  

Also, in this particular case, calling two root-level mutations synchronously is valid according to the GraphQL spec.  I would expect this operation not to have surfaced a violation.  

Is there a workaround to allow generation of persisted query manifest entries for documents containing multiple root level mutations?

### PR DESCRIPTION
**Pull request by jerelmiller**
Fixes #431

Better reports errors if they originate from Apollo Client itself rather than throwing an obscure error during the manifest generation. This change also adds detects multiple operations in a single document and will report those as errors.

### CODE REVIEW

File: packages/generate-persisted-query-manifest/src/index.ts [hunk 1]
```diff
@@ -482,13 +500,20 @@ export async function generatePersistedQueryManifest(
...
     visit(source.node, {
       OperationDefinition(node) {
         const name = node.name?.value;
 
+        if (++documentCount > 1) {
+          addError(source, ERROR_MESSAGES.multipleOperations());
+          return BREAK;
+        }
+
         if (!name) {
```
Comment (glasser) [inline packages/generate-persisted-query-manifest/src/index.ts:517]: Hmm, I'm wondering why we don't have any sort of error or warning on anonymous operations rather than just not including them in the manifest and having them break...

File: packages/generate-persisted-query-manifest/src/index.ts [hunk 2]
```diff
@@ -482,13 +500,20 @@ export async function generatePersistedQueryManifest(
...
+
     // We delegate validation to the functions that return the document sources.
     // We just need to record the operations here to sort them in the manifest
     // output.
     visit(source.node, {
       OperationDefinition(node) {
         const name = node.name?.value;
 
+        if (++documentCount > 1) {
+          addError(source, ERROR_MESSAGES.multipleOperations());
```
Comment (glasser) [inline packages/generate-persisted-query-manifest/src/index.ts:513]: Should we put the error on the second operation node as opposed to on "source" which appears in test to mean that all errors are showing up as `1:1`?

File: packages/generate-persisted-query-manifest/src/index.ts (hunk 1 above)
Comment (jerelmiller) [reply packages/generate-persisted-query-manifest/src/index.ts:517]: Hmmm, I'm not sure I follow what you're asking (or I'm reading your comment wrong). Currently we error on anonymous operations and force you to name all of them. Here is a test that shows this behavior: https://github.com/apollographql/apollo-utils/blob/930dee9b49e0d143e80aa610c68474ff2fed453e/packages/generate-persisted-query-manifest/src/__tests__/cli.test.ts#L1255-L1277

Are you seeing something different in testing?

File: packages/generate-persisted-query-manifest/src/index.ts (hunk 2 above)
Comment (jerelmiller) [reply packages/generate-persisted-query-manifest/src/index.ts:513]: Looking back through the implementation of [`addError`](https://github.com/apollographql/apollo-utils/blob/930dee9b49e0d143e80aa610c68474ff2fed453e/packages/generate-persisted-query-manifest/src/index.ts#L266-L272), it looks like we really don't care about `node` in that output and only use `file` and `location` as part of the error message, so it doesn't look like it would matter which `node` we use here.

On the note about errors 1:1 with operation nodes, I considered that (and actually implemented that first), but I found this only makes sense if we include the operation name in the error output, otherwise the error just looks repetitive. Here is what something like that looks like:

```ts
  expect(stderr).toMatchInlineSnapshot(`
    [
      "src/mixed.graphql",
      "1:1  error  Cannot declare multiple operations in a single document. Please remove the 'TestQuery' operation or move it into a different document.",
      "1:1  error  Cannot declare multiple operations in a single document. Please remove the 'TestSubscription' operation or move it into a different document.",
      "src/mutations.graphql",
      "1:1  error  Cannot declare multiple operations in a single document. Please remove the 'SayGoodbye' operation or move it into a different document.",
      "src/queries.graphql",
      "1:1  error  Cannot declare multiple operations in a single document. Please remove the 'GoodbyeQuery' operation or move it into a different document.",
      "src/subscriptions.graphql",
      "1:1  error  Cannot declare multiple operations in a single document. Please remove the 'GoodbyeSubscription' operation or move it into a different document.",
      "✖ 5 errors",
    ]
  `);

```

vs what it is now:

```ts
  expect(stderr).toMatchInlineSnapshot(`
    [
      "src/mixed.graphql",
      "1:1  error  Cannot declare multiple operations in a single document.",
      "src/mutations.graphql",
      "1:1  error  Cannot declare multiple operations in a single document.",
      "src/queries.graphql",
      "1:1  error  Cannot declare multiple operations in a single document.",
      "src/subscriptions.graphql",
      "1:1  error  Cannot declare multiple operations in a single document.",
      "✖ 4 errors",
    ]
  `);
```

Thoughts?

File: packages/generate-persisted-query-manifest/src/index.ts (hunk 1 above)
Comment (jerelmiller) [reply packages/generate-persisted-query-manifest/src/index.ts]: Finally realized what I was missing which is that this check was done in a different code block that traversed the AST in `fromFilepathList`. For now I moved the check for the number of operations into that same codeblock. It looks like GraphQL Codegen will split those operations into separate entries in the manifest.

If we decide to include a fail-safe and would prefer we don't allow this at all, we can move the check back and update the comment explaining why we do this check in the original place rather than moving it to the function that returns the document sources.

**Comment by jerelmiller** [comment]
@glasser would love for you to take another look here 🙂. Let me know if the latest change alleviates your concerns.

**Review by glasser — APPROVED** [review]
